# Generated by Django 4.1.5 on 2023-01-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.DateField(auto_now_add=True),
        ),
    ]
